package ebook.entity;

import java.util.Date;

public class Books {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.color
     *
     * @mbg.generated
     */
    private Integer color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.shopName
     *
     * @mbg.generated
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.writer
     *
     * @mbg.generated
     */
    private String writer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.remains
     *
     * @mbg.generated
     */
    private Integer remains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.remarkNum
     *
     * @mbg.generated
     */
    private Integer remarknum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.saleNum
     *
     * @mbg.generated
     */
    private Integer salenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.ISBN
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.valid
     *
     * @mbg.generated
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.cover
     *
     * @return the value of books.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.cover
     *
     * @param cover the value for books.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.price
     *
     * @return the value of books.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.price
     *
     * @param price the value for books.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.title
     *
     * @return the value of books.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.title
     *
     * @param title the value for books.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.color
     *
     * @return the value of books.color
     *
     * @mbg.generated
     */
    public Integer getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.color
     *
     * @param color the value for books.color
     *
     * @mbg.generated
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.shopName
     *
     * @return the value of books.shopName
     *
     * @mbg.generated
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.shopName
     *
     * @param shopname the value for books.shopName
     *
     * @mbg.generated
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.writer
     *
     * @return the value of books.writer
     *
     * @mbg.generated
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.writer
     *
     * @param writer the value for books.writer
     *
     * @mbg.generated
     */
    public void setWriter(String writer) {
        this.writer = writer == null ? null : writer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.remains
     *
     * @return the value of books.remains
     *
     * @mbg.generated
     */
    public Integer getRemains() {
        return remains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.remains
     *
     * @param remains the value for books.remains
     *
     * @mbg.generated
     */
    public void setRemains(Integer remains) {
        this.remains = remains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.remarkNum
     *
     * @return the value of books.remarkNum
     *
     * @mbg.generated
     */
    public Integer getRemarknum() {
        return remarknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.remarkNum
     *
     * @param remarknum the value for books.remarkNum
     *
     * @mbg.generated
     */
    public void setRemarknum(Integer remarknum) {
        this.remarknum = remarknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.saleNum
     *
     * @return the value of books.saleNum
     *
     * @mbg.generated
     */
    public Integer getSalenum() {
        return salenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.saleNum
     *
     * @param salenum the value for books.saleNum
     *
     * @mbg.generated
     */
    public void setSalenum(Integer salenum) {
        this.salenum = salenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.ISBN
     *
     * @return the value of books.ISBN
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.ISBN
     *
     * @param isbn the value for books.ISBN
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.intro
     *
     * @return the value of books.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.intro
     *
     * @param intro the value for books.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.time
     *
     * @return the value of books.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.time
     *
     * @param time the value for books.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.valid
     *
     * @return the value of books.valid
     *
     * @mbg.generated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.valid
     *
     * @param valid the value for books.valid
     *
     * @mbg.generated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}