package ebook.entity.entity;

import ebook.entity.OrderitemKey;

public class Orderitem extends OrderitemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.num
     *
     * @return the value of orderitem.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.num
     *
     * @param num the value for orderitem.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}