package ebook.entity;

public class OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Sto_id
     *
     * @mbg.generated
     */
    private String stoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Del_id
     *
     * @mbg.generated
     */
    private String delId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Sto_id
     *
     * @return the value of orders.Sto_id
     *
     * @mbg.generated
     */
    public String getStoId() {
        return stoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Sto_id
     *
     * @param stoId the value for orders.Sto_id
     *
     * @mbg.generated
     */
    public void setStoId(String stoId) {
        this.stoId = stoId == null ? null : stoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Del_id
     *
     * @return the value of orders.Del_id
     *
     * @mbg.generated
     */
    public String getDelId() {
        return delId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Del_id
     *
     * @param delId the value for orders.Del_id
     *
     * @mbg.generated
     */
    public void setDelId(String delId) {
        this.delId = delId == null ? null : delId.trim();
    }
}