package ebook.entity;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.use_password
     *
     * @mbg.generated
     */
    private String usePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.identity
     *
     * @mbg.generated
     */
    private Integer identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.valid
     *
     * @mbg.generated
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.address
     *
     * @return the value of users.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.address
     *
     * @param address the value for users.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.use_password
     *
     * @return the value of users.use_password
     *
     * @mbg.generated
     */
    public String getUsePassword() {
        return usePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.use_password
     *
     * @param usePassword the value for users.use_password
     *
     * @mbg.generated
     */
    public void setUsePassword(String usePassword) {
        this.usePassword = usePassword == null ? null : usePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.identity
     *
     * @return the value of users.identity
     *
     * @mbg.generated
     */
    public Integer getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.identity
     *
     * @param identity the value for users.identity
     *
     * @mbg.generated
     */
    public void setIdentity(Integer identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.valid
     *
     * @return the value of users.valid
     *
     * @mbg.generated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.valid
     *
     * @param valid the value for users.valid
     *
     * @mbg.generated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}