spring:
  datasource:
#   数据源基本配置
    username: root
    password: MyNewPass
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml

#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
