package ebook.entity;

public class ItemsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.order_id
     *
     * @return the value of items.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.order_id
     *
     * @param orderId the value for items.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.book_id
     *
     * @return the value of items.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.book_id
     *
     * @param bookId the value for items.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}